// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 车辆维保数据
type VehicleMaintenance struct {
	// 维保时间
	MaintenanceDate *time.Time `json:"maintenance_date"`
	// 维保公里数
	MaintenanceKilometers *float64 `json:"maintenance_kilometers"`
}
